### ISSUE TITLE
Why is the implementation method exposed?

### ISSUE THREAD

**Issue by annevk** [WICG/performance-measure-memory#6] opened 2020-02-26 13:45 UTC
It seems problematic to expose whether something is JS or DOM as this makes it harder to change implementation technique.

**Comment by bzbarsky** [comment] 2020-02-26 15:23
Indeed, Gecko had `Promise` as "dom" and then switched it to "js" in implementation terms, and for Streams some parts are "js" and some are "dom".  In Servo, all "dom" objects are actually allocated on the "js" heap.

At the very least, there needs to be an explicit definition of what "dom" and "js" mean here, because right now it's not clear at all whether those are meant to refer to implementation, specification, or something else.

**Comment by ulan** [comment] 2020-02-26 15:51
The value of each `type` field is implementation dependent, so the implementation can choose the memory type granularity. (In general I think we should not try to standardize the breakdown part beside its format).

The following two results would be valid from the spec point of view:
```javascript
{
  bytes: 100*MB,
  breakdown: [ ]
}

{
  bytes: 100*MB,
  breakdown: [
    {bytes: 40*MB, type: 'window', attribution: ['https://foo.com']},
    {bytes: 30*MB, type: 'window', attribution: ['https://bar.com/iframe']},
    {bytes: 20*MB, type: 'worker', attribution: ['https://foo.com/worker']},
    {bytes: 10*MB, type: 'window', attribution: ['https://foo.com', 'https://bar.com/iframe']},
  ]
}
```

**Comment by bzbarsky** [comment] 2020-02-26 16:16
See, "worker" vs "window" makes sense as a conceptual difference.  "js" vs "dom" really does not.

Having implementation-dependent types here seems like a recipe for interop problems to me...

**Comment by ulan** [comment] 2020-02-26 17:05
That's a good point! I didn't consider the conceptual difference.

Having "js" vs "dom" would make triaging memory regressions easier for the developers, but that's not worth the interop sacrifice IMO.

What would be in the list of the standard types? I am thinking "window", "worker", "gpu", "shared".
We could also refine "worker" into "dedicated-worker", "shared-worker", "service-worker".

**Comment by ulan** [comment] 2020-03-04 12:02
After talking to web developers and discussing this with @domenic, I think the idea of cross-UA-compatible types is a lost cause.

It is important for developers to get fine-grained types to narrow down memory regressions. The set of types proposed in PR #7 is too coarse-grained to be useful. Even for such a small set it will be difficult to reach consensus among the implementers.

With UA-specific types browsers can provide more actionable grouping of memory if they have that information readily available, e.g. group by `String`, `ArrayBuffer`, `Code`, `EventListener`, `DetachedNodes`.

@domenic suggested to emphasize that the field is UA-specific by naming it `userAgentSpecificType` and keep the contents of the field unspecified. IMO interop risks are not critical here because there is not much a developer can do with this field besides storing it in the telemetry data.

Another option is to have one standard field for the global scope (window, worker, shared) and one UA-specific field that gives more details.

**Comment by bzbarsky** [comment] 2020-03-05 21:04
> emphasize that the field is UA-specific by naming it userAgentSpecificType

That seems like it would help, yes.

> because there is not much a developer can do with this field besides storing it in the telemetry data

They can use the string in the field to index into some object they are using to track stuff, and end up with an exception when the string is not in the set they expect, for example.  We've had interop problems from much more convoluted website hacks...

So I wouldn't just wave off the interop issue here.

**Comment by ulan** [comment] 2020-10-19 16:52
Fixed by the commits above: "type" is renamed to "userAgentSpecificType".

**Closed by ulan** 2020-10-19 16:52 UTC
