### ISSUE TITLE
Make scope naming case consistent across values

### ISSUE THREAD

**Issue by npm1** [WICG/performance-measure-memory#21] opened 2020-12-09 14:09 UTC
It seems the values can be "Window", "DedicatedWorkerGlobalScope", "SharedWorkerGlobalScope", "ServiceWorkerGlobalScope" or "cross-origin-aggregated". The last one is inconsistent with the other ones. Per https://w3ctag.github.io/design-principles/#casing-rules I think we want all of them to be lower-case-dash-delimited?

**Comment by domenic** [comment] 2020-12-09 20:27
Yeah, this is a bit of a weird corner of the API. The others are global object names, and I encouraged @ulan to use them instead of inventing new dash-delimited versions such as "window", "dedicated-worker", "shared-worker", "service-worker". As you can see in [the spec steps that set these values](https://wicg.github.io/performance-measure-memory/#creating-a-new-memory-attribution), it's designed so that it'll work on any global automatically, which feels like good architecture.

But then, indeed, cross-origin-aggregated is different from all the others. I tend to think that's OK, since it _is_ an exceptional case. Maybe there's a better option though...

**Comment by ulan** [comment] 2020-12-10 13:24
What if we turn cross-origin aggregated into a message: "Cross-origin scope is not revealed due to security" to make it clear that is an exceptional case and not one of the values?

**Comment by npm1** [comment] 2020-12-10 13:38
I think that's still not consistent, right? Given that the enumeration convention is not being followed, my opinion is that the odd one out should just follow the same casing as the rest, so it could be `"CrossOriginAggregated"`.

**Comment by domenic** [comment] 2020-12-10 15:03
But I think the inconsistency is a feature, not a bug: one of these things is different than the others, so it _should_ use a different naming convention.

**Comment by ulan** [comment] 2020-12-10 16:53
I also think of "cross-origin-aggregated" as a value outside the scope enum.

In TypeScript I would express the type of `scope` as `ScopeEnum | String`, so it either holds an enum value or an error message.

**Comment by ulan** [comment] 2020-12-15 17:42
Closing as WAI

**Closed by ulan** 2020-12-15 17:42 UTC
